'use client';

import { useState, useCallback, useEffect, useRef } from 'react';
import { PrintExpandedView as PkgPrintExpandedView } from '@cai-crete/print-components';
import type { PrintSaveResult, PrintToolbarTools, SelectedImage, PrintDraftState } from '@cai-crete/print-components';
import type { CanvasNode } from '@/types/canvas';

export interface PrintGenerateResult {
  thumbnailBase64: string;
}

interface Props {
  node: CanvasNode;
  onCollapse: () => void;
  onGeneratingChange?: (v: boolean) => void;
  onGeneratePrintComplete?: (result: PrintGenerateResult) => void;
  onPrintNodeUpdate?: (updates: Partial<CanvasNode>) => void;
  autoGenerate?: boolean;
  initialDraftState?: PrintDraftState | null;
}

const IC = { stroke: 'currentColor', fill: 'none', strokeWidth: 1.6, strokeLinecap: 'round' as const, strokeLinejoin: 'round' as const };

const IconUndo     = () => <svg viewBox="0 0 20 20" {...IC}><path d="M7 14L4 11L7 8" /><path d="M4 11H13A4 4 0 1 1 13 19" /></svg>;
const IconRedo     = () => <svg viewBox="0 0 20 20" {...IC}><path d="M13 14L16 11L13 8" /><path d="M16 11H7A4 4 0 1 0 7 19" /></svg>;
const IconLibrary  = () => <svg viewBox="0 0 20 20" {...IC}><rect x="3" y="4" width="6" height="7" rx="1" /><rect x="11" y="4" width="6" height="7" rx="1" /><rect x="3" y="13" width="6" height="3" rx="1" /><rect x="11" y="13" width="6" height="3" rx="1" /></svg>;
const IconSave     = () => <svg viewBox="0 0 20 20" {...IC}><path d="M4 4H14L16 6V17A1 1 0 0 1 15 18H5A1 1 0 0 1 4 17V4Z" /><rect x="7" y="4" width="6" height="4" /><rect x="6" y="11" width="8" height="7" /></svg>;
const IconCollapse = () => <svg viewBox="0 0 20 20" {...IC}><path d="M16 10H4M9 5L4 10L9 15" /></svg>;
const IconChevronUp   = () => <svg viewBox="0 0 20 20" {...IC}><polyline points="4,13 10,7 16,13" /></svg>;
const IconChevronDown = () => <svg viewBox="0 0 20 20" {...IC}><polyline points="4,7 10,13 16,7" /></svg>;

function parseNodeImage(raw: string): SelectedImage {
  let current  = raw;
  let mimeType: SelectedImage['mimeType'] = 'image/jpeg';
  while (current.startsWith('data:')) {
    const semi  = current.indexOf(';');
    const comma = current.indexOf(',');
    if (semi === -1 || comma === -1) break;
    mimeType = current.slice(5, semi) as SelectedImage['mimeType'];
    current  = current.slice(comma + 1);
  }
  return { id: 'node-image', base64: current.replace(/\s/g, ''), mimeType, filename: 'source.jpg' };
}

export default function PrintExpandedView({
  node,
  onCollapse,
  onGeneratePrintComplete,
  onPrintNodeUpdate,
  autoGenerate,
  initialDraftState,
}: Props) {
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const hasAutoGenerated = useRef(false);

  useEffect(() => {
    const handler = (e: KeyboardEvent) => { if (e.key === 'Escape') onCollapse(); };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [onCollapse]);

  // 패키지가 initialAction='generate'를 no-op으로 구현해 두어,
  // DOM에서 GENERATE 버튼을 직접 클릭해 자동 생성을 트리거한다.
  useEffect(() => {
    if (!autoGenerate || hasAutoGenerated.current) return;
    const timer = setTimeout(() => {
      const btn = Array.from(document.querySelectorAll<HTMLButtonElement>('button'))
        .find(b => b.textContent?.trim() === 'GENERATE' && !b.disabled);
      if (btn) {
        btn.click();
        hasAutoGenerated.current = true;
      }
    }, 300);
    return () => clearTimeout(timer);
  }, [autoGenerate]);

  // 저장된 이미지가 있으면 우선 사용, 없으면 generatedImageData 사용
  const selectedImages: SelectedImage[] = node.printSelectedImages
    ? node.printSelectedImages
    : node.generatedImageData ? [parseNodeImage(node.generatedImageData)] : [];

  // 저장 완료 → Canvas 썸네일 + 문서 상태 업데이트
  const handleSave = useCallback((result: PrintSaveResult) => {
    onGeneratePrintComplete?.({ thumbnailBase64: result.thumbnail });
    onPrintNodeUpdate?.({
      printSavedState: {
        html: result.html,
        mode: result.mode,
        metadata: result.metadata,
        savedAt: new Date().toISOString(),
      },
    });
  }, [onGeneratePrintComplete, onPrintNodeUpdate]);

  // 이미지 변경 콜백 → Canvas 노드에 저장
  const handleImagesChange = useCallback((images: SelectedImage[]) => {
    onPrintNodeUpdate?.({ printSelectedImages: images });
  }, [onPrintNodeUpdate]);

  // Canvas 전용 커스텀 툴바 (X 버튼 제거 — 사이드바 ← 버튼으로 대체)
  const renderToolbarWrapper = useCallback((tools: PrintToolbarTools) => {
    const toolBtnBase: React.CSSProperties = {
      width: 36, height: 36, border: 'none', borderRadius: '50%',
      background: 'transparent', cursor: 'pointer',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      color: 'var(--color-gray-500)', transition: 'color 100ms ease',
      flexShrink: 0,
    };

    return (
      <div
        style={{
          position: 'fixed',
          top: '50%',
          left: 'var(--gap-global, 1rem)',
          transform: 'translateY(-50%)',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          gap: 'var(--gap-global, 1rem)',
          zIndex: 1100,
        }}
      >
        {/* 툴 Pill: Undo / Redo / Library */}
        <div
          style={{
            display: 'flex', flexDirection: 'column', alignItems: 'center',
            padding: '0.5rem', gap: '0.25rem',
            backgroundColor: 'var(--color-white, #fff)',
            borderRadius: '2rem',
            boxShadow: '0 4px 6px -1px rgba(0,0,0,.1)',
          }}
        >
          <button
            title="실행 취소"
            disabled={!tools.canUndo}
            onClick={tools.onUndo}
            style={{ ...toolBtnBase, opacity: tools.canUndo ? 1 : 0.35, cursor: tools.canUndo ? 'pointer' : 'default' }}
          >
            <span style={{ width: 16, height: 16, display: 'flex' }}><IconUndo /></span>
          </button>
          <button
            title="다시 실행"
            disabled={!tools.canRedo}
            onClick={tools.onRedo}
            style={{ ...toolBtnBase, opacity: tools.canRedo ? 1 : 0.35, cursor: tools.canRedo ? 'pointer' : 'default' }}
          >
            <span style={{ width: 16, height: 16, display: 'flex' }}><IconRedo /></span>
          </button>
          <div style={{ width: '1.5rem', height: '1px', backgroundColor: '#e5e7eb', margin: '0.125rem auto' }} />
          <button
            title="라이브러리"
            onClick={tools.onOpenLibrary}
            style={toolBtnBase}
          >
            <span style={{ width: 16, height: 16, display: 'flex' }}><IconLibrary /></span>
          </button>
        </div>

        {/* 저장 버튼 */}
        <button
          title="저장"
          onClick={tools.onSave}
          style={{
            width: '2.75rem', height: '2.75rem', borderRadius: '50%',
            backgroundColor: 'var(--color-black, #111)',
            border: 'none',
            color: 'var(--color-white, #fff)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            cursor: 'pointer',
            boxShadow: '0 4px 6px -1px rgba(0,0,0,.2)',
            flexShrink: 0,
          }}
        >
          <span style={{ width: 16, height: 16, display: 'flex' }}><IconSave /></span>
        </button>
      </div>
    );
  }, []);

  // ExpandedSidebar 스타일 사이드바 래퍼 (← 버튼 + PRINT 탭)
  // position: fixed + top: 5rem — 패키지 Sidebar.tsx와 동일한 기준점 사용
  const renderSidebarWrapper = useCallback((content: React.ReactNode) => {
    const pillBase: React.CSSProperties = {
      background: 'var(--color-white)', borderRadius: 'var(--radius-pill)',
      boxShadow: 'var(--shadow-float)', flexShrink: 0,
    };
    const hoverOn  = (e: React.MouseEvent<HTMLButtonElement>) =>
      (e.currentTarget.style.backgroundColor = 'var(--color-gray-100)');
    const hoverOff = (e: React.MouseEvent<HTMLButtonElement>) =>
      (e.currentTarget.style.backgroundColor = 'transparent');

    return (
      <div style={{
        position: 'fixed',
        right: 'var(--gap-global, 1rem)',
        top: '5rem',
        bottom: 'var(--gap-global, 1rem)',
        width: 'var(--sidebar-w)',
        display: 'flex',
        flexDirection: 'column',
        gap: 'var(--gap-global, 1rem)',
        zIndex: 90,
      }}>
        {/* 헤더 행 */}
        <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'stretch', flexShrink: 0 }}>
          {/* ← 버튼 (Canvas로 복귀) */}
          <div style={{ ...pillBase, width: 'var(--h-cta-lg)', height: 'var(--h-cta-lg)' }}>
            <button
              onClick={onCollapse}
              title="캔버스로 돌아가기"
              style={{
                width: '100%', height: '100%', display: 'flex', alignItems: 'center',
                justifyContent: 'center', border: 'none', background: 'transparent',
                cursor: 'pointer', borderRadius: 'var(--radius-pill)',
                color: 'var(--color-gray-500)', transition: 'background-color 100ms ease, color 100ms ease',
              }}
              onMouseEnter={e => { hoverOn(e); e.currentTarget.style.color = 'var(--color-black)'; }}
              onMouseLeave={e => { hoverOff(e); e.currentTarget.style.color = 'var(--color-gray-500)'; }}
            >
              <span style={{ width: 20, height: 20, display: 'flex' }}><IconCollapse /></span>
            </button>
          </div>

          {/* PRINT 탭 (접기/펼치기) */}
          <div style={{ ...pillBase, flex: 1 }}>
            <button
              onClick={() => setSidebarOpen(v => !v)}
              title={sidebarOpen ? '패널 접기' : '패널 펼치기'}
              style={{
                width: '100%', height: 'var(--h-cta-lg)', display: 'flex',
                alignItems: 'center', justifyContent: 'space-between',
                padding: '0 0.875rem 0 1rem', border: 'none', background: 'transparent',
                cursor: 'pointer', borderRadius: 'var(--radius-pill)',
                transition: 'background-color 100ms ease',
              }}
              onMouseEnter={hoverOn}
              onMouseLeave={hoverOff}
            >
              <span className="text-title" style={{ color: 'var(--color-black)', letterSpacing: '0.04em' }}>
                PRINT
              </span>
              <span style={{ width: 16, height: 16, display: 'flex', color: 'var(--color-gray-500)', flexShrink: 0 }}>
                {sidebarOpen ? <IconChevronUp /> : <IconChevronDown />}
              </span>
            </button>
          </div>
        </div>

        {/* 본문: overflow hidden + 내부 스크롤 구조 (패키지 Sidebar.tsx 패턴 동일) */}
        {sidebarOpen && (
          <div style={{
            background: 'var(--color-white)', borderRadius: 'var(--radius-box)',
            boxShadow: 'var(--shadow-float)', flex: 1, minHeight: 0,
            overflow: 'hidden', display: 'flex', flexDirection: 'column',
          }}>
            <div style={{ flex: 1, overflowY: 'auto', minHeight: 0 }}>
              {/* block wrapper로 h-full 순환 참조를 끊어 content가 자연 높이로 자라도록 함 */}
              <div style={{ padding: '1.25rem' }}>
                {content}
              </div>
            </div>
          </div>
        )}
      </div>
    );
  }, [onCollapse, sidebarOpen]);

  return (
    <div style={{ flex: 1, overflow: 'hidden' }}>
      <PkgPrintExpandedView
        selectedImages={selectedImages}
        savedState={node.printSavedState}
        apiBaseUrl="/api/print-proxy"
        initialAction={autoGenerate ? 'generate' : undefined}
        initialDraftState={initialDraftState ?? undefined}
        onSave={handleSave}
        onDelete={onCollapse}
        onCurrentImagesChange={handleImagesChange}
        renderToolbarWrapper={renderToolbarWrapper}
        renderSidebarWrapper={renderSidebarWrapper}
      />
    </div>
  );
}
